flask_blog/posts/forms.py
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length

from flask_wtf import FlaskForm

class NewPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(max=100)])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class UpdatePostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(max=100)])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Update')

flask_blog/users/forms.py
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError

from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user

from ..models import User

class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=3)])
    password_conf = PasswordField('Confirm Password', validators=[DataRequired(), Length(min=3), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        if User.query.filter_by(username=username.data).first():
            raise ValidationError('That username is already taken.')

    def validate_email(self, email):
        if User.query.filter_by(email=email.data).first():
            raise ValidationError('That email is already taken.')

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

class UpdateAccountForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    profile_pic = FileField('Change Profile Picture', validators=[FileAllowed(['jpg', 'png', 'jpeg', 'gif'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            if User.query.filter_by(username=username.data).first():
                raise ValidationError('That username is already taken.')

    def validate_email(self, email):
        if email.data != current_user.email:
            if User.query.filter_by(email=email.data).first():
                raise ValidationError('That email is already taken.')

class RequestPasswordResetForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Send Reset Email')

    def validate_email(self, email):
        if not User.query.filter_by(email=email.data).first():
            raise ValidationError('Sorry, we could not find an account associated with that email.')

class PasswordResetForm(FlaskForm):
    password = PasswordField('New Password', validators=[DataRequired(), Length(min=3)])
    password_conf = PasswordField('Confirm Password', validators=[DataRequired(), Length(min=3), EqualTo('password')])
    submit = SubmitField('Reset Password')

flask_blog/main/routes.py
from flask import Blueprint, redirect, url_for, request, render_template

from ..models import Post

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    return redirect(url_for('main.home'))

@bp.route('/home')
def home():
    page = request.args.get('page', default=1, type=int)
    posts = Post.query.order_by(Post.post_date.desc()) # Arranged in descending order
    return render_template('home.html', posts=posts.paginate(per_page=5, page=page))

@bp.route('/about')
def about():
    return render_template('about.html', title='About')

flask_blog/posts/routes.py
from flask import Blueprint, flash, redirect, url_for, render_template, abort, request
from flask_login import login_required, current_user

from .. import db
from ..models import Post
from .forms import NewPostForm, UpdatePostForm

bp = Blueprint('posts', __name__)

@bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = NewPostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('edit_post.html', title='New Post', name='New Post', form=form)

@bp.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@bp.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = UpdatePostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post updated!', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('edit_post.html', title=post.title, name='Update Post', form=form)

@bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted!', 'success')
    return redirect(url_for('main.home'))

flask_blog/users/routes.py
import os

from flask import Blueprint, current_app, redirect, url_for, flash, render_template, request
from flask_login import login_required, login_user, logout_user, current_user

from .. import db, bcrypt
from ..models import User, Post
from .forms import RegisterForm, LoginForm, UpdateAccountForm, RequestPasswordResetForm, PasswordResetForm
from .utils import send_pw_reset_email, save_profile_pic

bp = Blueprint('users', __name__)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()
    if form.validate_on_submit():
        password_hash = bcrypt.generate_password_hash(form.password.data)
        user = User(username=form.username.data, email=form.email.data, password=password_hash)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}! You can now log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            return redirect(url_for('main.home'))
        flash('Login unsuccessful. Check username or password.', 'danger')
    return render_template('login.html', title='Login', form=form)

@bp.route('/reset_password', methods=['GET', 'POST'])
def request_pw_reset():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestPasswordResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_pw_reset_email(user)
        flash('An email has been send with password reset instructions.', 'success')
        return redirect(url_for('users.login'))
    return render_template('request_reset.html', title='Reset Password', form=form)

@bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def pw_reset(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_pw_reset_token(token)
    if not user:
        flash('That is an invalid or expired token.', 'danger')
        return redirect(url_for('users.request_pw_reset'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        password_hash = bcrypt.generate_password_hash(form.password.data)
        user.password = password_hash
        db.session.commit()
        flash('Password successfully changed! You can now log in with your new password.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_pw.html', title='Reset Password', form=form)

@bp.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        if form.profile_pic.data:
            if current_user.profile_pic != 'default.jpg':
                os.remove(os.path.join(current_app.root_path, 'static', current_user.profile_pic))
            current_user.profile_pic = save_profile_pic(form.profile_pic.data)
        db.session.commit()
        flash('Account info updated.', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    img_file = url_for('static', filename=current_user.profile_pic)
    return render_template('account.html', title='Account', img_file=img_file, form=form)

@bp.route('/user/<username>')
def user(username):
    page = request.args.get('page', default=1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.post_date.desc())
    return render_template('user.html', title=username, posts=posts.paginate(per_page=5, page=page), user=user)

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout successful.', 'success')
    return redirect(url_for('main.home'))

flask_blog/templates/about.html
{% extends 'page.html' %}

{% block content %}
    <h1>About</h1>
    <hr>
    <p>
        Welcome to Flask Blog. This is a website created by Shaunak Warty using Python and the Flask module.
        This website is modeled off of <a href="https://www.youtube.com/watch?v=MwZwr5Tvyxo&list=PL-osiE80TeTs4UjLw5MM6OjgkjFeUxCYH">Corey Schafer's Flask tutorial</a>, available on Youtube.
        You can see this website's code <a href="https://github.com/hyperXcube/flask-blog">here</a>.
        We hope you like this website, and if you have any comments or improvements to my website, you can email Shaunak at shaunak.warty@gmail.com.
    </p>
{% endblock %}

flask_blog/templates/account.html
{% extends 'page.html' %}

{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ img_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <form method="post" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}

                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}

                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.profile_pic.label }}

                {{ form.profile_pic(class='form-control-file') }}
                {% if form.profile_pic.errors %}
                    {% for error in form.profile_pic.errors %}
                        <span class="text-danger">{{ error }}</span><br>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock %}

flask_blog/templates/edit_post.html
{% extends 'page.html' %}

{% block content %}
    <div class="content-section">
        <form method="post" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ name }}</legend>
                <div class="form-group">
                    {{ form.title.label(class='form-control-label') }}

                    {% if form.title.errors %}
                        {{ form.title(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class='form-control-label') }}

                    {% if form.content.errors %}
                        {{ form.content(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock %}

flask_blog/templates/home.html
{% extends 'page.html' %}

{% block content %}
    <h1>Home</h1>
    <hr>

    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename=post.author.profile_pic) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.post_date.strftime('%B %d, %Y at %I:%M %p') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}

    {% for page_n in posts.iter_pages(left_edge=1, right_edge=2, left_current=1, right_current=2) %}
        {% if page_n %}
            {% if posts.page == page_n %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_n) }}">{{ page_n }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_n) }}">{{ page_n }}</a>
            {% endif %}
        {% else %}
            . . .
        {% endif %}
    {% endfor %}

{% endblock %}

flask_blog/templates/login.html
{% extends 'page.html' %}

{% block content %}
    <div class="content-section">
        <form method="post" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}

                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}

                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class='form-check-input') }}
                    {{ form.remember.label(class='form-check-label') }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
                <small class="text-muted ml-2">
                    <a href = "{{ url_for('users.request_pw_reset') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
        </small>
    </div>
{% endblock %}

flask_blog/templates/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='page.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <!-- Nav bar -->
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Flask Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">{{ current_user.username }}</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.user', username=current_user.username) }}">My Posts</a>
                            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <!-- Side bar -->
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}

                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Sidebar</h3>

                    <p class="text-muted">More stuff will go here in the near future
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Item 1</li>
                            <li class="list-group-item list-group-item-light">Item 2</li>
                            <li class="list-group-item list-group-item-light">Item 3</li>
                            <li class="list-group-item list-group-item-light">Item 4</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>

    <!-- Bootstrap JS -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

flask_blog/templates/post.html
{% extends 'page.html' %}

{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename=post.author.profile_pic) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.post_date.strftime('%B %d, %Y at %I:%M %p') }}</small>
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
            {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mr-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>

                    <!-- Delete Modal -->
                    <button class="btn btn-danger btn-sm ml-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    <!-- From Bootstrap website -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this post? This action can't be undone.
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="post">
                                        <input class="btn btn-danger" type="submit" value="Delete">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </article>
{% endblock %}

flask_blog/templates/register.html
{% extends 'page.html' %}

{% block content %}
    <div class="content-section">
        <form method="post" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register</legend>
                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}

                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}

                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}

                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password_conf.label(class='form-control-label') }}

                    {% if form.password_conf.errors %}
                        {{ form.password_conf(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.password_conf.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password_conf(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Login</a>
        </small>
    </div>
{% endblock %}

flask_blog/templates/user.html
{% extends 'page.html' %}

{% block content %}
    <h1>Posts by {{ user.username }} ({{ posts.total }})</h1>
    <hr>

    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename=post.author.profile_pic) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.post_date.strftime('%B %d, %Y at %I:%M %p') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}

    {% for page_n in posts.iter_pages(left_edge=1, right_edge=2, left_current=1, right_current=2) %}
        {% if page_n %}
            {% if posts.page == page_n %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user', username=user.username, page=page_n) }}">{{ page_n }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user', username=user.username, page=page_n) }}">{{ page_n }}</a>
            {% endif %}
        {% else %}
            . . .
        {% endif %}
    {% endfor %}

{% endblock %}